systemConfig:
  retainData: true
  applicationName: minimal
  adminEmail: admin@example.com
  llmConfig:
    streaming: false
    qaChainConfig:
      modelConfig:
        provider: bedrock
        modelId: anthropic.claude-3-haiku-20240307-v1:0
      promptTemplate: |
        You are a helpful assistant.
        Context:
        ${context}
        Question: ${question}
      promptVariables:
        - context
        - question
  ragConfig:
    vectorStoreConfig:
      vectorStoreType: s3vectors
      vectorStoreProperties:
        distanceMetric: cosine
    embeddingsModels:
      - provider: bedrock
        modelId: cohere.embed-multilingual-v3
        modelRefKey: cohere.embed-multilingual-v3
        dimensions: 1024
    corpusConfig:
      corpusType: knowledgebase
  chatHistoryConfig:
    storeType: dynamodb
  
