systemConfig:
    retainData: true
    applicationName: minimal
    adminEmail: admin@example.com
    llmConfig:
        streaming: false
        qaChainConfig:
            modelConfig:
                provider: bedrock
                modelId: anthropic.claude-3-haiku-20240307-v1:0
            promptTemplate: |
                You are a helpful assistant.
                Context:
                ${context}
                Question: ${question}
            promptVariables:
                - context
                - question
    ragConfig:
        vectorStoreConfig:
            vectorStoreType: s3vectors
            vectorStoreProperties:
                distanceMetric: cosine
                metadataConfiguration:
                    nonFilterableMetadataKeys:
                        - AMAZON_BEDROCK_TEXT
                        - AMAZON_BEDROCK_METADATA
                        - x-amz-bedrock-kb-source-uri
                        - x-amz-bedrock-kb-data-source-id
                        - x-amz-bedrock-kb-document-page-number
                        - x-amz-bedrock-kb-chunk-id
        embeddingsModels:
            - provider: bedrock
              modelId: amazon.titan-embed-text-v2:0
              modelRefKey: titan-embed-text-v2
              dimensions: 1024
        corpusConfig:
            corpusType: knowledgebase
    chatHistoryConfig:
        storeType: dynamodb
