systemConfig:
    retainData: false
    llmConfig:
        streaming: false
        maxConversationHistory: 5
        maxCorpusDocuments: 5
        corpusSimilarityThreshold: 0.5
        standaloneChainConfig:
            modelConfig:
                provider: bedrock
                modelId: anthropic.claude-3-7-sonnet-20250219-v1:0
                modelKwargs:
                    maxTokens: 1024
                    temperature: 0.1
                    topP: 0.99
                    stopSequences:
                        - 'Asisstant:'
            promptTemplate: |
                Given the following conversation and a follow-up question, rephrase the follow-up question into a concise standalone question. Return the rephrased question in JSON format.
                Chat History:
                ---
                ${chat_history}
                ---
                Follow Up Input: ${question}
                Standalone question:
            promptVariables:
                - chat_history
                - question
        qaChainConfig:
            modelConfig:
                provider: bedrock
                modelId: anthropic.claude-3-7-sonnet-20250219-v1:0
                modelKwargs:
                    maxTokens: 1024
                    temperature: 0.1
                    topP: 0.99
                    stopSequences:
                        - 'Asisstant:'
            promptTemplate: |
                You are an AI assistant for question answering tasks. Use the following context to answer the question. If you don't know the answer, just say "I don't know".

                Question: ${question}
                Context: 
                ---
                ${context}
                ---
                Answer:
            promptVariables:
                - question
                - context
    ragConfig:
        vectorStoreConfig:
            vectorStoreType: s3vectors
            vectorStoreProperties:
                distanceMetric: cosine
        embeddingsModels:
            - provider: bedrock
              modelId: amazon.titan-embed-text-v2:0
              modelRefKey: titan-embed-text-v2
              dimensions: 1024
        corpusConfig:
            corpusType: knowledgebase
    wafConfig:
        enableApiGatewayWaf: true
